on:
  push: 
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:       
    - uses: actions/checkout@v4.1.1
    - uses: devops-actions/actionlint@c0ee017f8abef55d843a647cd737b87a1976eb69 #v0.1.1
      continue-on-error: true
      id: action-lint
    
    - uses: actions/upload-artifact@v4.3.1
      with:
        name: actionlint-results
        path: ${{ steps.action-lint.outputs.results-file }}
