# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "dependency1"
        versions: ["1.2.3"] # ignore updates to version 1.2.3 of dependency1
      - dependency-name: "dependency2"
        versions: ["4.5.6"] # ignore updates to version 4.5.6 of dependency2

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
